sylius_grid:
    grids:
        setono_sylius_cms_admin_page:
            driver:
                options:
                    class: "%setono_sylius_cms.model.page.class%"
            limits: [100, 250, 500, 1000]
            fields:
                title:
                    type: string
                    label: setono_sylius_cms.ui.title
                code:
                    type: string
                    label: sylius.ui.code
                internalDescription:
                    type: string
                    label: setono_sylius_cms.ui.internal_description
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [ code, internalDescription, translations.title ]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    preview:
                        type: setono_cms_preview_page
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
