sylius_grid:
    grids:
        setono_sylius_cms_admin_carousel:
            driver:
                options:
                    class: "%setono_sylius_cms.model.carousel.class%"
            limits: [100, 250, 500, 1000]
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                internalDescription:
                    type: string
                    label: setono_sylius_cms.ui.internal_description
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [ code ]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
