setono_sylius_cms_admin_block:
    resource: |
        section: admin
        alias: setono_sylius_cms.block
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        permission: true
        grid: setono_sylius_cms_admin_block
        vars:
            all:
                header: setono_sylius_cms.ui.block_header
                subheader: setono_sylius_cms.ui.block_subheader
                templates:
                    form: "@SetonoSyliusCMSPlugin/admin/block/_form.html.twig"
    type: sylius.resource

setono_sylius_cms_admin_page:
    resource: |
        section: admin
        alias: setono_sylius_cms.page
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        permission: true
        grid: setono_sylius_cms_admin_page
        vars:
            all:
                header: setono_sylius_cms.ui.page_header
                subheader: setono_sylius_cms.ui.page_subheader
                templates:
                    form: "@SetonoSyliusCMSPlugin/admin/page/_form.html.twig"
    type: sylius.resource

setono_sylius_cms_admin_template:
    resource: |
        section: admin
        alias: setono_sylius_cms.template
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        permission: true
        grid: setono_sylius_cms_admin_template
        vars:
            all:
                header: setono_sylius_cms.ui.template_header
                subheader: setono_sylius_cms.ui.template_subheader
                templates:
                    form: "@SetonoSyliusCMSPlugin/admin/template/_form.html.twig"
    type: sylius.resource

setono_sylius_cms_admin_view_update:
    path: /views/{id}/edit
    methods: [ GET, PUT ]
    defaults:
        _controller: setono_sylius_cms.controller.view::updateWithViewModelAction
        _sylius:
            section: admin
            redirect: setono_sylius_cms_admin_view_update
            permission: true
            template: '@SyliusAdmin/Crud/update.html.twig'
            vars:
                header: setono_sylius_cms.ui.view_header
                subheader: setono_sylius_cms.ui.view_subheader
                templates:
                    form: '@SetonoSyliusCMSPlugin/admin/view/_form.html.twig'

setono_sylius_cms_admin_view_create:
    path: /views/new
    methods: [ GET, POST ]
    defaults:
        _controller: setono_sylius_cms.controller.view::createWithViewModelAction
        _sylius:
            section: admin
            redirect: setono_sylius_cms_admin_view_update
            permission: true
            template: '@SyliusAdmin/Crud/create.html.twig'
            vars:
                header: setono_sylius_cms.ui.view_header
                subheader: setono_sylius_cms.ui.view_subheader
                templates:
                    form: '@SetonoSyliusCMSPlugin/admin/view/_form.html.twig'

setono_sylius_cms_admin_view:
    resource: |
        section: admin
        alias: setono_sylius_cms.view
        templates: "@SyliusAdmin\\Crud"
        except: [update, create]
        redirect: index
        permission: true
        grid: setono_sylius_cms_admin_view
        vars:
            all:
                header: setono_sylius_cms.ui.view_header
                subheader: setono_sylius_cms.ui.view_subheader
                templates:
                    form: "@SetonoSyliusCMSPlugin/admin/view/_form.html.twig"
    type: sylius.resource

setono_sylius_cms_admin_ajax_paths:
    resource: 'admin/ajax.yaml'
    prefix: /ajax
