setono_sylius_cms_admin_block:
    resource: |
        section: admin
        alias: setono_sylius_cms.block
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        permission: true
        grid: setono_sylius_cms_admin_block
        vars:
            all:
                header: setono_sylius_cms.ui.block_header
                subheader: setono_sylius_cms.ui.block_subheader
    type: sylius.resource
