setono_sylius_cms_admin_ajax:
    resource: 'admin/ajax.yaml'
    prefix: /ajax

setono_sylius_cms_admin_block:
    resource: admin/block.yml

setono_sylius_cms_admin_asset:
    resource: |
        section: admin
        alias: setono_sylius_cms.asset
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        permission: true
        grid: setono_sylius_cms_admin_asset
        vars:
            all:
                header: setono_sylius_cms.ui.asset_header
                subheader: setono_sylius_cms.ui.asset_subheader
                templates:
                    form: "@SetonoSyliusCMSPlugin/admin/asset/_form.html.twig"
    type: sylius.resource

setono_sylius_cms_admin_asset_upload_from_editor:
    path: /assets/upload-from-editor
    methods: [ POST ]
    controller: setono_sylius_cms.controller.action.admin.upload_editor_picture

setono_sylius_cms_admin_carousel:
    resource: |
        section: admin
        alias: setono_sylius_cms.carousel
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        permission: true
        grid: setono_sylius_cms_admin_carousel
        vars:
            all:
                header: setono_sylius_cms.ui.carousel_header
                subheader: setono_sylius_cms.ui.carousel_subheader
                templates:
                    form: "@SetonoSyliusCMSPlugin/admin/carousel/_form.html.twig"
    type: sylius.resource

setono_sylius_cms_admin_page:
    resource: |
        section: admin
        alias: setono_sylius_cms.page
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        permission: true
        grid: setono_sylius_cms_admin_page
        vars:
            all:
                header: setono_sylius_cms.ui.page_header
                subheader: setono_sylius_cms.ui.page_subheader
                templates:
                    form: "@SetonoSyliusCMSPlugin/admin/page/_form.html.twig"
            index:
                icon: file alternate outline
            update:
                templates:
                    form: "@SetonoSyliusCMSPlugin/admin/page/_form.html.twig"
                    toolbar: "@SetonoSyliusCMSPlugin/admin/page/update/_toolbar.html.twig"
    type: sylius.resource

# This route must be defined before the 'setono_sylius_cms_admin_template' resource below
setono_sylius_cms_admin_template_editor:
    path: /templates/editor/{id}
    methods: [GET]
    defaults:
        id: null
        _controller: setono_sylius_cms.controller.action.admin.template_editor

setono_sylius_cms_admin_template:
    resource: |
        section: admin
        alias: setono_sylius_cms.template
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        permission: true
        grid: setono_sylius_cms_admin_template
        vars:
            all:
                header: setono_sylius_cms.ui.template_header
                subheader: setono_sylius_cms.ui.template_subheader
                templates:
                    form: "@SetonoSyliusCMSPlugin/admin/template/_form.html.twig"
            index:
                icon: columns
    type: sylius.resource

setono_sylius_cms_admin_update_element_redirect:
    path: /element/update/{type}/{code}
    methods: [GET]
    defaults:
        _controller: setono_sylius_cms.controller.action.admin.update_element_redirect
