imports:
    - { resource: "@SetonoSyliusCMSPlugin/Resources/config/grids/setono_sylius_cms_admin_asset.yaml" }
    - { resource: "@SetonoSyliusCMSPlugin/Resources/config/grids/setono_sylius_cms_admin_block.yaml" }
    - { resource: "@SetonoSyliusCMSPlugin/Resources/config/grids/setono_sylius_cms_admin_carousel.yaml" }
    - { resource: "@SetonoSyliusCMSPlugin/Resources/config/grids/setono_sylius_cms_admin_page.yaml" }
    - { resource: "@SetonoSyliusCMSPlugin/Resources/config/grids/setono_sylius_cms_admin_template.yaml" }
    - { resource: "@SetonoSyliusCMSPlugin/Resources/config/grids/setono_sylius_cms_admin_view.yaml" }

sylius_ui:
    events:
        setono_sylius_cms.admin.view.update.javascripts:
            blocks:
                javascripts:
                    template: '@SetonoSyliusCMSPlugin/admin/view/_javascripts.html.twig'
        setono_sylius_cms.admin.view.create.javascripts:
            blocks:
                javascripts:
                    template: '@SetonoSyliusCMSPlugin/admin/view/_javascripts.html.twig'

sylius_grid:
    templates:
        action:
            setono_cms_preview_page: '@SetonoSyliusCMSPlugin/admin/grid/action/page/preview.html.twig' 
