imports:
    - { resource: "@SetonoSyliusCMSPlugin/Resources/config/grids/setono_sylius_cms_admin_asset.yaml" }
    - { resource: "@SetonoSyliusCMSPlugin/Resources/config/grids/setono_sylius_cms_admin_block.yaml" }
    - { resource: "@SetonoSyliusCMSPlugin/Resources/config/grids/setono_sylius_cms_admin_carousel.yaml" }
    - { resource: "@SetonoSyliusCMSPlugin/Resources/config/grids/setono_sylius_cms_admin_page.yaml" }
    - { resource: "@SetonoSyliusCMSPlugin/Resources/config/grids/setono_sylius_cms_admin_template.yaml" }

parameters:
    setono_sylius_cms.asset_adapter: "setono_sylius_cms_asset"

knp_gaufrette:
    adapters:
        setono_sylius_cms_asset:
            local:
                directory: "%sylius_core.public_dir%/media/assets/original"
                create: true
    filesystems:
        setono_sylius_cms_asset:
            adapter: "%setono_sylius_cms.asset_adapter%"

liip_imagine:
    loaders:
        setono_sylius_cms_asset:
            filesystem:
                data_root: "%sylius_core.public_dir%/media/assets/original"
                allow_unresolvable_data_roots: true # The Gaufrette library will create the path when needed, hence the directory will be available when we need it for LiipImagineBundle
    resolvers:
        setono_sylius_cms_asset:
            web_path:
                web_root: "%sylius_core.public_dir%"
                cache_prefix: "media/assets/cache"
    filter_sets:
        setono_sylius_cms_admin_asset_thumbnail:
            data_loader: setono_sylius_cms_asset
            cache: setono_sylius_cms_asset
            quality: 80
            filters:
                thumbnail: { size: [75, 75], mode: outbound }

sylius_grid:
    templates:
        action:
            setono_cms_preview_page: '@SetonoSyliusCMSPlugin/admin/grid/action/page/preview.html.twig'
            setono_cms_duplicate_block: '@SetonoSyliusCMSPlugin/admin/grid/action/block/duplicate.html.twig'
