name: "Backwards Compatibility Check"

on:
    push:
        branches:
            - "master"
        paths-ignore:
            - "**/*.md"
    pull_request:
        paths-ignore:
            - "**/*.md"
    workflow_dispatch: ~

jobs:
    backwards-compatibility-check:
        runs-on: "ubuntu-latest"
        
        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2"
    
            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
                    php-version: "latest"
    
            -   name: "Run BC checks"
                uses: "Setono/roave-backwards-compatibility-check-action@master"
